apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: drsconfigs.lcm.mirantis.com
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: lcm.mirantis.com
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1alpha1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              required:
                - reconcileInterval
                - collector
                - scheduler
                - mover
              type: object
              properties:
                reconcileInterval:
                  type: integer
                collector:
                  type: object
                  properties:
                    name:
                      type: string
                  required:
                    - name
                  x-kubernetes-preserve-unknown-fields: true
                scheduler:
                  type: object
                  properties:
                    name:
                      type: string
                  required:
                    - name
                  x-kubernetes-preserve-unknown-fields: true
                mover:
                  type: object
                  properties:
                    name:
                      type: string
                  required:
                    - name
                  x-kubernetes-preserve-unknown-fields: true
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: drsconfigs
    # singular name to be used as an alias on the CLI and for display
    singular: drsconfig
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: DRSConfig
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
      - drs
    categories:
      - all
