apiVersion: lcm.mirantis.com/v1alpha1
kind: DRSConfig
metadata:
  name: test
  namespace: openstack
spec:
  reconcileInterval: 300
  collector:
    name: poc
  scheduler:
    name: poc
    load_threshold: 30
  mover:
    name: poc
