apiVersion: lcm.mirantis.com/v1alpha1
kind: DRSConfig
metadata:
  name: test
  namespace: openstack
spec:
  reconcileInterval: 300
  collector:
    name: stacklight
  scheduler:
    name: ease-most-loaded
    load_threshold: 7
  mover:
    name: os-live-migration
